src-cljs/storefront/components/home.cljs
We now offer Peruvian in all textures of hair so the text here needed
to be updated to reflect that
=> Change featured product banner text

resources/public/content/help.html, src-cljs/storefront/components/shop_by_look.cljs
disregard the title of this branch (i don’t know how to change the
title of the branch!)
- this change is to lower case all the other titles to match the
homepage and about us page styling
=> Update case of titles on Info Pages

src-cljc/storefront/components/home.cljc
The Fonts were incorrect on initial images…this update has the correct
fonts/sizing
=> Update Desktop Feature Blocks

src-cljc/storefront/components/home.cljc
we sold out of the 12” look so we are updating to the 14” look image
and link to look detail page
=> Update Feature Block to 14"

src-cljc/storefront/components/home.cljc
360 frontals are now being marketed to our users…this hero update is a
part of letting everyone know!
=> Update Hero For 360 Launch

src-cljc/storefront/components/home.cljc
The current feature block links to a 14in water wave look…that product
is now sold out….this is to update to a deal we have plenty of stock
=> Update Feature Block WaterWave12

src-cljc/storefront/components/home.cljc
this is an alternative hero for loose wave
=> Update Hero for New Hero

src-cljc/storefront/components/home.cljc
Changed the block images for both:
- left block for the WW14
- right block to include the length on the image (not changing the
look/sale item
- updated look on the left block
=> Update Feature Blocks for Water Wave 14

src-cljc/storefront/components/home.cljc
To advertise the wig launch on our homepage, we have changed out the
images for mobile and desktop, updated the alt tags, and changed the
link of the hero to go to the wigs category page.
=> Update Hero Image and Link for Wigs Launch [#nodeps]

src-cljc/storefront/components/home.cljc
just changing it up to show a different hair style
=> Updating the homepage hero to a blue hero for wigs [#nodeps]

src-cljc/storefront/components/home.cljc
=> Update hero image to pink wigs hero [#nodeps]

src-cljc/storefront/components/home.cljc
BYS14 is sold out…this is to update the image and look id to a BYS10
look/deal
=> Update Right Feature Block to BYS10

src-cljc/storefront/components/home.cljc
removed the shine from the models forehead.
=> Change the SOUL hero for a hero that has minor photo touch ups [#nodeps]

src-cljc/catalog/categories.cljc, src-cljc/catalog/product_details.cljc
- updated hero on category page for bright pink hero
- added copy to PDP promotion copy to include ‘will be donated’
=> Update Wigs Category Hero + PDP Promotion Copy for Bright Pink [#nodeps]

src-cljc/storefront/components/home.cljc, src-cljs/storefront/config.cljs, src/storefront/config.clj
NOTE: these assets are larger than what we currently have in these
feature blocks.  I played with them in my inspector and it just worked
without interrupting the rest of the page layout.  we should double
check to make sure that is correct.
basically we want square blocks on mobile and larger landscape blocks
on desktop.
=> Update feature blocks for Straight and Body Wave bundle deals [#nodeps]

src-cljc/catalog/categories.cljc
- Dyed Virgin Hair
- Dyed Virgin Closures
- Dyed Virgin Frontals
=> Update the OG and Meta Tags for Dyed Hair Category Pages [#nodeps]

resources/public/content/our-hair.html
Our hair is not 'single donor' so we have removed that copy from this page
=> Update Hair Page Copy - No Single Donor

resources/public/pinterest-67ca9.html
It needs to be left in forever, so a public file keeps it out of the way.
[#nodeps]
=> Add pinterest site verification

src-cljc/storefront/components/footer.cljc
- change from 12 to 10
- update font size to 12px
- add underline
=> Edit Essence copy in footer to be bigger and new price

src-cljc/storefront/components/footer.cljc
needed to also apply this to DTC
=> Essence footer text decoration

src-cljc/adventure/stylist_matching/stylist_profile.cljc
Change the share text to be from the users first person voice.
=> Update share-icon text

src-cljc/stylist_matching/match_stylist.cljc
Remove 'Welcome!' from the title to not be so repetative
=> Update match-stylist title

src-cljc/catalog/icp.cljc
Remove copy about Wig Customization and other small tweaks.
=> Update Copy on Wig ICP

src-cljc/storefront/components/footer.cljc, src-cljc/ui/promo_banner.cljc
- new covid19 copy to be more strict
- new essence copy to let the users know how they get it...you need to place an order
=> Updated copy for promo bar and essence copy

src-cljc/catalog/categories.cljc, src-cljc/catalog/product_details.cljc, src-cljc/checkout/shop/cart_v202004.cljc, src-cljs/storefront/components/shop_by_look_details.cljs
- update copy where we say 'Install' to now say 'Service'
- update category 23 meta data
=> Copy update from Install to Service

src-cljc/checkout/shop/cart_v202004.cljc, src-cljs/checkout/confirmation.cljs
on /cart and /checkout/confirm
=> Updating total incentive label

src-cljs/storefront/components/checkout_complete.cljs
Update copy to 'within 3 business days' to match Concierge correspondence with customers
=> Update business days on order complete page
